config/routes.rb
NsgThesis::Application.routes.draw do
  scope "(:locale)", :locale => /en|fi/ do
    match "/auth/:provider/callback" => "sessions#create"
    match "/signin" => "sessions#signin", :as => :signin
    match "/signout" => "sessions#destroy", :as => :signout
    match "/myevents" => "events#my_events", :as => :myevents
  
  resources :events do
    resources :comments
    resources :galleries
    resources :hotels
    get 'unapproved', :on => :collection
    get 'approve', :on => :member
    get 'feed', :on => :collection
    get 'recent', :on => :collection
    get 'most_watched', :on => :collection
    get 'nearby', :on => :collection
    get 'upcoming', :on => :collection
    get 'like', :on => :member
  end

  resources :tags
  resources :categories
  resources :search do
    get 'advanced', :on => :collection
  end

  resources :ads do
    get 'unconfirmed', :on => :collection
    get 'confirm', :on => :member
    get 'my', :on => :collection
  end
  
  resources :clients do
    get 'unconfirmed', :on => :collection
    get 'confirm', :on => :member
  end

    root :to => 'home#index'
  end

end

app/views/shared/_comment.html.erb
<div id="comment-<%= comment.id %>">
  <% if comment.user.name %>
    <p class="comment-commenter"><%= comment.user.try(:name) %>
  <% else %>
    <p class="comment-commenter"><%= t 'title.anonymous' %>
  <% end %>
  <% if is_admin? || (current_user && current_user.has_comment?(comment)) %>
    <span style="float:right;padding-right:20px;"><%= link_to (image_tag 'edit.png'), edit_event_comment_path(@commentable, comment) %></span>
    <span style="float:right;padding-left:15px;"><%= link_to (image_tag 'delete.gif'), [@commentable, comment], :confirm => I18n.t('help.delete_confirm_comment'), :method => :delete %></span>
  <% end %></p>
  <% if comment.user.avatar %>
    <p class="comment-avatar"><%= image_tag comment.user.try(:avatar) %></p>
  <% else %>
    <p class="comment-avatar"><%= image_tag ('user_no_image.png') %></p>
  <% end %>
  <p class="comment-created_at"><%= l comment.created_at, :format => :long if comment.created_at? %></p>
  <p class="comment-body"><%= comment.body %></p>
</div>

app/views/shared/_event_tab_nav.html.erb
<header>
  <h1><%= event.name %></h1>
</header>

<div class="eventTab">
<ul class="clearfix"> 
  <li><%= link_to I18n.t('title.event_info'), event, :class => set_active_if_controller('events') %></li>
  <li><%= link_to I18n.t('title.comments'), event_comments_path(event), :class => set_active_if_controller('comments') %></li>
  <li><%= link_to I18n.t('title.gallery'), event_galleries_path(event), :class => set_active_if_controller('galleries') %></li>
  <li><%= link_to I18n.t('title.hotels'), event_hotels_path(event), :class => set_active_if_controller('hotels') %></li> 
</ul>
</div>

app/views/shared/_providers_list.html.erb
<ul id="providers_list">
    <li><%= link_to "/auth/facebook" do %><%= image_tag "facebook_64.png", :size => "64x64", :alt => "Facebook" %><% end %></li>
    <li><%= link_to "/auth/twitter" do %><%= image_tag "twitter_64.png", :size => "64x64", :alt => "Twitter" %><% end %></li>
    <li><%= link_to "/auth/google" do %><%= image_tag "google_64.png", :size => "64x64", :alt => "Google" %><% end %></li>
    <li><%= link_to "/auth/github" do %><%= image_tag "github_64.png", :size => "64x64", :alt => "Github" %><% end %></li>
    <li><%= link_to "/auth/yahoo" do %><%= image_tag "yahoo_64.png", :size => "64x64", :alt => "Yahoo" %><% end %></li>
    <li><%= link_to "/auth/aol" do %><%= image_tag "aol_64.png", :size => "64x64", :alt => "Aol" %><% end %></li>
    <li><%= link_to "/auth/myopenid" do %><%= image_tag "openid_64.png", :size => "64x64", :alt => "MyOpenID" %><% end %></li>
</ul>

app/views/shared/_socialmedia_buttons.html.erb
  <li>
      <div class="g-plusone" data-size="small" data-annotation="none" callback="incrementEventLikedCount" data-href="<%= event_path(event) %>"></div>
  </li>    
  <li>
      <div style="margin:-4px -1px 0 0; padding: 0;" class="fb-like" data-href="<%= event_path(event) %>" data-layout="button_count" data-send="false" data-width="90" data-show-faces="false"></div>
  </li>
</ul>

<div id="fb-root"></div>
<script type="text/javascript">
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) {return;}
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/fi_FI/all.js#xfbml=1&appId=271203636242426";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

<script type="text/javascript">
  window.___gcfg = {lang: '<%= I18n.locale.to_s %>'};

  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>