config/routes.rb
NsgThesis::Application.routes.draw do
  scope "(:locale)", :locale => /en|fi/ do
    match "/auth/:provider/callback" => "sessions#create"
    match "/signin" => "sessions#signin", :as => :signin
    match "/signout" => "sessions#destroy", :as => :signout
    match "/myevents" => "events#my_events", :as => :myevents
  
  resources :events do
    resources :comments
    resources :galleries
    resources :hotels
    get 'unapproved', :on => :collection
    get 'approve', :on => :member
    get 'feed', :on => :collection
    get 'recent', :on => :collection
    get 'most_watched', :on => :collection
    get 'nearby', :on => :collection
    get 'upcoming', :on => :collection
    get 'like', :on => :member
  end

  resources :tags
  resources :categories
  resources :search do
    get 'advanced', :on => :collection
  end

  resources :ads do
    get 'unconfirmed', :on => :collection
    get 'confirm', :on => :member
    get 'my', :on => :collection
  end
  
  resources :clients do
    get 'unconfirmed', :on => :collection
    get 'confirm', :on => :member
  end

    root :to => 'home#index'
  end

end

app/models/event.rb
require 'nodejs_notifier'

class Event < ActiveRecord::Base
  has_many :showtimes, :dependent => :destroy
  has_many :comments, :as => :commentable, :dependent => :destroy
  
  has_many :categorizations
  has_many :categories, :through => :categorizations
  
  has_many :galleries, :dependent => :destroy

  has_many :taggings, :as => :taggable
  has_many :tags, :through => :taggings

  belongs_to :submitter, :polymorphic => true

  after_create :notify_created
  after_update :notify_updated
  after_destroy :notify_removed
  validate :check_active_times, :if => Proc.new { |r| r.active_time_start_changed? or r.active_time_end_changed? }

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :reprocess_picture, :if => :cropping?

  has_attached_file :picture, :styles => { :thumb => "40x40#", :small => "100x100#", :medium => "200x200#", :info => "200x200>", :crop => "300x300>", :large => "800x800>" }, :processors => [:cropper]

  before_save :set_active_datetimes, :set_address_and_city
  
  accepts_nested_attributes_for :showtimes, :galleries, :categories, :reject_if => :all_blank, :allow_destroy => true
  
  validates_presence_of :name, :description, :country, :address

  scope :most_watched, where('times_watched > ?', 0).order('times_watched desc').limit(50)
  scope :popular, where('liked_count > ?', 0).order('liked_count desc').limit(50)
  scope :recent, where('created_at >= ?', Time.zone.now - 1.week).order('created_at DESC')
  scope :upcoming, joins(:showtimes).where('showtimes.start_time >= ?', Time.zone.now - 2.days).select('distinct events.*').order('showtimes.start_time ASC')
  scope :between, lambda { |from, to| where('created_at between ? and ?', from, to) }
  scope :approved, where(:approved => true)
  scope :unapproved, where(:approved => false)
  scope :active, where('active_time_start <= ? and active_time_end >= ?', Time.zone.now + 10.minutes, Time.zone.now)

  define_index do
    indexes :name
    indexes description
    indexes city
    indexes address
    indexes country
    indexes comments.body, :as => :comment_body
    indexes tags(:name), :as => :tag_name
    indexes submitter(:name), :as => :submitter_name

    has "RADIANS(longitude)", :as => :longitude, :type => :float
    has "RADIANS(latitude)", :as => :latitude, :type => :float
    has showtimes(:start_time), :as => :start_time

    set_property :longitude_attr, :as => :longitude
    set_property :latitude_attr, :as => :latitude

    where sanitize_sql(['approved', true])
  end

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  def tag_names=(tag_names)
    tag_names.each do |tag_name|
      tag = Tag.find_or_initialize_by_name(tag_name.downcase)
      tags << tag if tag
    end
  end

  def set_address_and_city
    address_and_city_parts = []
    address_and_city_parts << self[:address] if self[:address]
    address_and_city_parts << self[:city] if self[:city]
    self[:address_and_city] = ""
    self[:address_and_city] = address_and_city_parts.join(', ')
  end

  def set_active_datetimes
    self[:active_time_start] = Time.zone.now + 10.minutes if self[:active_time_start].blank?
    self[:active_time_end] = Time.zone.now + 1.week if self[:active_time_end].blank?
  end

  def check_active_times
    if !self[:active_time_start].blank? && self[:active_time_start] < Time.zone.now
      errors.add(:active_time_start, I18n.t('custom_errors.cant_be_past'))
    end

    if !self[:active_time_end].blank? && self[:active_time_end] < Time.zone.now
      errors.add(:active_time_end, I18n.t('custom_errors.cant_be_past'))
    end

    if !self[:active_time_start].blank? && !self[:active_time_end].blank?
      if self[:active_time_end] < self[:active_time_start]
        errors.add(:active_time_end, I18n.t('custom_errors.cant_be_earlier'))
      end
    end
  end

  def approve!
    self[:approved] = true
    save!
  end

  def small_picture_url
    picture.url(:small)
  end

  def as_json(options = {})
    super(options).merge(:picture => small_picture_url)
  end

  def to_param
    "#{id}-#{name.downcase.gsub(/[^[:alnum:]]/,'-')}".gsub(/-{2,}/,'-')
  end

  def has_picture?
    !self.picture.url.include?('missing')
  end

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def picture_geometry(style = :original)
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(picture.path(style))
  end

  def to_json_with_showtimes
    to_json(:include => :showtimes)
  end

  private
    def notify_updated
      NodejsNotifier.notify('/event_updated', to_json_with_showtimes) unless self.times_watched_changed?
    end

    def notify_created
      NodejsNotifier.notify('/event_added', to_json_with_showtimes)
    end
  
    def notify_removed
      NodejsNotifier.notify('/event_removed', to_json_with_showtimes)
    end

    def reprocess_picture
      picture.reprocess!
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :login_required, :except => [:index, :show, :feed, :recent, :most_watched, :nearby, :upcoming, :like]
  before_filter :admin_required, :only => [:unapproved, :approve]

  add_breadcrumb I18n.t('title.events'), :events_path
  
  def index
    @events = Event.approved.recent	
  end

  def recent
    @events = Event.approved.recent

    respond_to do |format|
      format.html { render :template => 'events/index' }
      format.js { render :template => 'events/filter_result' }
    end
  end

  def most_watched
    @events = Event.approved.most_watched

    respond_to do |format|
      format.html { render :template => 'events/index' }
      format.js { render :template => 'events/filter_result'  }
    end
  end

  def nearby
    use_ip = !(params[:location].present? && params[:location].split(',').size == 2)
    location = use_ip ? request.env['REMOTE_ADDR'] : params[:location].split(',').map { |l| l.to_f }

    @events = Event.approved.near(location, 20, :units => :km)

    respond_to do |format|
      format.html { render :template => 'events/index' }
      format.js { render :template => 'events/filter_result' }
    end
  end

  def upcoming
    @events = Event.approved.upcoming

    respond_to do |format|
      format.html { render :template => 'events/index' }
      format.js { render :template => 'events/filter_result' }
    end
  end

  def feed
    @events = Event.approved.includes(:categories).includes(:showtimes).limit(50).order('active_time_start DESC')

    respond_to do |wants|
      wants.rss { render :layout => false }
    end
  end

  def like
    @event = Event.find(params[:id])
    @event.increment!(:liked_count, 1)

    respond_to do |format|
      format.html { redirect_to :back }
      format.js { render :status => :ok }
    end
  end

  def new
    add_breadcrumb I18n.t('title.new_event'), :new_event_path    
    @event = Event.new 
    
    @event.categories.build
    @event.showtimes.build
  end
  
  def create
    params[:event][:category_ids] ||= []

    @event = Event.new(params[:event])
    @event.submitter = current_user

    if @event.save
      if @event.submitter.client_id.nil?
        #UserMailer.event_sent_to_admin(@event, @event.submitter).deliver
      else
        @event.approve!
        #UserMailer.event_published(@event, @event.submitter).deliver
        #UserMailer.notice_admin(@event, @event.submitter).deliver
      end

      message = @event.approved? ? I18n.t('notice.event_published') : I18n.t('notice.event_added')

      if params[:event][:picture].blank?
        redirect_to events_path, :flash => { :success => message }
      else
        render :crop
      end
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id], :include => :showtimes)
    @event.increment!(:times_watched, 1)
    @comment = @event.comments.build
    add_breadcrumb @event.name, event_path(@event)
  end
  
  def edit
    @event = Event.find(params[:id])
    add_breadcrumb I18n.t('title.edit_event'), :edit_event_path
  end
  
  def update
    @event = Event.find(params[:id], :include => { :galleries => :gallery_resources })
    ids = params[:event][:category_ids]
    params[:event][:category_ids] = (ids || []) + @event.category_ids
    params[:event][:category_ids].uniq!

    if @event.update_attributes!(params[:event])
      if params[:event][:picture].blank?
        redirect_to @event, :flash => { :success => I18n.t('notice.event_updated') }
      else
        render :crop
      end
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    
    redirect_to :back, :flash => { :success => I18n.t('notice.event_deleted') }
  end

  def unapproved
    @events = Event.unapproved
    add_breadcrumb I18n.t('title.unapproved_events'), :unapproved_events_path
  end

  def approve
    @event = Event.find(params[:id])
    @event.approve!
    UserMailer.event_published(@event, @event.submitter).deliver
    redirect_to unapproved_events_path, :flash => { :success => I18n.t('notice.event_approved') }
  end
  
  def my_events
    add_breadcrumb I18n.t('my_links.my_events'), :myevents_path
    @my_events = current_user.all_events.order('created_at DESC')
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def get_city(address)
    address = @event.address
    city = address.split(',', 2).last
    return city
  end

  def set_active_if_controller(controller)
    controller == params[:controller] ? 'active_tab' : nil
  end

  def event_image_width(event, options)
    dimensions = event.picture_geometry(options[:style])
    options[:image_width].to_i - (options[:image_width].to_i - dimensions.width.to_i)
  end

  def event_info_width(event, options)
    return 660 unless event.has_picture?

    dimensions = event.picture_geometry(options[:style])
    options[:info_width].to_i + (options[:image_width].to_i - dimensions.width.to_i)
  end
end

app/views/events/_event.html.erb
<% show_record_info = nil unless defined?(show_record_info) %>

<article id="event-<%= event.id %>" class="event_list_entry <%= cycle('even', 'odd') %> clearfix">
  <div class="event_image">
  <a href="#"></a>
    <% if event.has_picture? %>
    <%= image_tag event.picture(:small), :id => "event-image-#{event.id}" %>
  <% end %>
  </div>
  <div class="event_info">
    <% if show_record_info %>
      <% if is_admin? && !event.approved? %>
        <div class="record_status"><span class="button_small_green"><%= link_to t('help.approve'), approve_event_path(event) %></span></div>
      <% elsif current_user && !is_admin? && current_user.has_event?(event) && !event.approved? %>
        <div class="record_status"><span class="button_small_red"><%= t('title.waiting_for_confirmation') %></span></div>
      <% end %>
    <% end %>

    <header>
      <h1>
        <%= link_to event.name, event, :id => "event-name-#{event.id}" %>
        <% if current_user %>
          <% if current_user.has_event?(event) %>
            <span class="icons-right"><%= link_to (image_tag 'delete.gif'), event, :confirm => I18n.t('help.delete_confirm_event'), :method => :delete %></span>            
            <span class="icons-right"><%= link_to (image_tag 'edit.png'), edit_event_path(event) %></span>
          <% end %>
        <% end %>
      </h1>
      <span class="event_showtime">
        <time datetime="<%= event.showtimes.first.start_time %>"><%= l event.showtimes.first.start_time, :format => :long %></time>

        <% unless event.showtimes.first.end_time.nil? %>
        -
        <time><%= l event.showtimes.first.end_time, :format => :long %></time>
        <% end %>

        <% if event.showtimes.count > 1 %>
          (<%= link_to(t('title.more_times'), event_path(event, :anchor => 'showtimes')) %>)
        <% end %>
      </span>
		</header>
      <p id="event-description-<%= event.id %>"><%= event.description %></p>
    

    <ul class="event_additional_info">
      <li>
        <span id="event-<%= event.id %>-category-list" class="event_category_list">
          <%= category_list(event.categories) %>
        </span>
      </li>
      <%= render :partial => 'shared/socialmedia_buttons', :locals => { :event => event } %>
    

</article>

app/views/events/_events.html.erb
<% render @events %>

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <%= f.error_messages %>

	  <p>
		  <%= f.label :name %><br />
      <%= f.text_field :name %>
		</p>
		
		<p>
		  <%= f.label :description %><br />
		  <%= f.text_area :description %>
		</p>

    <%= f.label :categories %><br />     
      <ul class="categories">
        <% Category.all.each do |category| %>
        <li>
          <%= check_box_tag 'event[category_ids][]', category.id, @event.categories.include?(category), :id => "category-#{category.id}" %>
          <%= label_tag "category-#{category.id}", category.name %>
        </li>
        <% end %>
      </ul>
    <p>
      <%= f.fields_for :showtimes do |builder| %>
        <%= render 'showtime_fields', :f => builder %>
      <% end %>
      <span class="add_showtime"><%= link_to_add_fields I18n.t("misc.add_showtime"), f, :showtimes %></span>
    </p>
    <p>
      <%= f.label :picture %><br />
      <% if !@event.new_record? && @event.has_picture? %>
        <%= image_tag @event.picture(:small) %><br />
      <% end %>
      <%= f.file_field :picture %>
    </p>
    <p>
      <%= f.label :country %><br />
      <%= f.country_select :country, ['Finland'] %>
    </p>
    
    <p>
      <%= f.label :address %><br />
      <%= f.text_field :address %>
    </p>
 
    <p class="start_time">
      <%= f.label :active_time_start %><br />
      <%= f.text_field :active_time_start, :class => "datepicker" %>
    </p>
    <p class="end_time">
      <%= f.label :active_time_end %><br />
      <%= f.text_field :active_time_end, :class => "datepicker" %>
    </p>
  
    <p class="submit_form">
		  <%= f.submit %>
		  <%= link_to 'Cancel', events_path %>
	  </p>
<% end %>

app/views/events/_showtime_fields.html.erb
<div class="showtime_fields" >
  <p class="start_time">
    <%= f.label :start_time %><br />
    <%= f.text_field :start_time, :class => "datepicker" %>
  </p>
  <p class="end_time">
    <%= f.label :end_time %><br />
    <%= f.text_field :end_time, :class => "datepicker" %>
  </p>
  <p class="remove_showtime">
    <%= link_to_remove_fields t('misc.remove'), f %>
  </p>
</div>

app/views/events/crop.html.erb
<h1>Crop image</h1>
<%= content_for(:head) do %>

<script type="text/javascript" charset="utf-8">
$(function() {
  $('#cropbox').Jcrop({
    onChange: update_crop,
    onSelect: update_crop,
    setSelect: [0, 0, 300, 300],
    aspectRatio: 1
  });
});

function update_crop(coords) {
  var rx = 100/coords.w;
  var ry = 100/coords.h;
  $('#preview').css({
    width: Math.round(rx * <%= @event.picture_geometry(:crop).width %>) + 'px',
    height: Math.round(ry * <%= @event.picture_geometry(:crop).height %>) + 'px',
    marginLeft: '-' + Math.round(rx * coords.x) + 'px',
    marginTop: '-' + Math.round(ry * coords.y) + 'px'
  });
  var ratio = <%= @event.picture_geometry(:original).width %> / <%= @event.picture_geometry(:crop).width %>;
  $("#crop_x").val(Math.round(coords.x * ratio));
  $("#crop_y").val(Math.round(coords.y * ratio));
  $("#crop_w").val(Math.round(coords.w * ratio));
  $("#crop_h").val(Math.round(coords.h * ratio));
}
</script>
<% end %>

<%= image_tag @event.picture(:crop), :id => "cropbox" %>

<h4>Preview:</h4>
<div style="width:100px; height:100px; overflow:hidden">
  <%= image_tag @event.picture(:crop), :id => "preview" %>
</div>

<%= form_for @event do |f| %>
  <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
    <%= f.hidden_field attribute, :id => attribute %>
  <% end %>
  <p><%= f.submit "Crop" %></p>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

app/views/events/filter_result.js.erb
$('#events').hide();
$("#events").html("<%= escape_javascript( render(:partial => 'event', :collection => @events) ) %>");
$('#events').fadeIn('fast');

app/views/events/index.html.erb
<% title t('title.events') %>

<header>
  <h1><%= t 'title.events' %></h1>
  <nav id="event_filter_nav">
    <ul>
      <li><%= link_to t('title.recent'), recent_events_path, :remote => true %></li>
      <li><%= link_to t('title.most_watched'), most_watched_events_path, :remote => true %></li>
      <li><%= link_to t('title.nearby'), nearby_events_path, :"data-location" => true, :remote => true %></li>
      <li><%= link_to t('title.upcoming'), upcoming_events_path, :remote => true %></li>
    </ul>
  </nav>
</header>

<div id="events">
<%- for event in @events -%>
<%= render event %>
<%- end -%>
</div>

app/views/events/my_events.html.erb
<header>
  <h1><%= t 'my_links.my_events' %></h1>
</header>

<%= render :partial => 'event', :collection => @my_events, :locals => { :show_record_info => true } %>

app/views/events/new.html.erb
<% title t('title.new_event') %>

<h1><%= t 'title.new_event' %></h1>

<%= render 'form' %>

app/views/events/show.html.erb
<% title @event.name %>

<%= render :partial => 'shared/event_tab_nav', :locals => { :event => @event } %>

  <div class="event_content clearfix">
     <div class="event-info" style="width: <%= event_info_width(@event, :style => :info, :info_width => 460, :image_width => 200) %>px;margin-bottom: 20px;">
      <p class="event-description">
        <%= @event.description %>
      </p>

      <h2><%= t 'title.where' %></h2>
      <p>
        <%= @event.address_and_city %> <a id="inline" href="#map"><%= t('help.show_map') %></a><br />
        <%= @event.country %>

        <div style="display:none"><div id="map"><%= image_tag "http://maps.google.com/maps/api/staticmap?size=600x480&sensor=false&zoom=14&markers=#{@event.latitude}%2C#{@event.longitude}" %></div></div>
      </p>

      <h2><%= I18n.t('title.showtimes') %></h2>
      <table>
        <% for showtime in @event.showtimes %>
        <tr>
          <td><%= l showtime.start_time, :format => :long2 %></td>
          <td style="width: 20px; text-align: center">-</td>
          <td><%= l(showtime.end_time, :format => :long2) if showtime.end_time %></td>
        </tr>
        <% end %>
      </table>

      <p class="event-category_list">
        <%= category_list(@event.categories) %>
      </p>    
    </div>

    <% if @event.has_picture? %>
      <p class="event-image" style="width: <%= event_image_width(@event, :style => :info, :image_width => 200) %>px;">
          <%= link_to image_tag(@event.picture(:info)), @event.picture.url(:large), :class => 'image' %>
      </p>
    <% end %> 
    
    <ul class="event_additional_info" style="float:left; margin-left:-10px">
      <%= render :partial => 'shared/socialmedia_buttons', :locals => { :event => @event } %>
    </ul>
    
  </div>

app/views/events/unapproved.html.erb
<header>
  <h1><%= t 'title.unapproved_events' %></h1>
</header>

<%= render :partial => 'event', :collection => @events, :locals => { :show_record_info => true } %>