config/routes.rb
NsgThesis::Application.routes.draw do
  scope "(:locale)", :locale => /en|fi/ do
    match "/auth/:provider/callback" => "sessions#create"
    match "/signin" => "sessions#signin", :as => :signin
    match "/signout" => "sessions#destroy", :as => :signout
    match "/myevents" => "events#my_events", :as => :myevents
  
  resources :events do
    resources :comments
    resources :galleries
    resources :hotels
    get 'unapproved', :on => :collection
    get 'approve', :on => :member
    get 'feed', :on => :collection
    get 'recent', :on => :collection
    get 'most_watched', :on => :collection
    get 'nearby', :on => :collection
    get 'upcoming', :on => :collection
    get 'like', :on => :member
  end

  resources :tags
  resources :categories
  resources :search do
    get 'advanced', :on => :collection
  end

  resources :ads do
    get 'unconfirmed', :on => :collection
    get 'confirm', :on => :member
    get 'my', :on => :collection
  end
  
  resources :clients do
    get 'unconfirmed', :on => :collection
    get 'confirm', :on => :member
  end

    root :to => 'home#index'
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations
  has_many :events, :through => :categorizations

  has_many :taggings, :as => :taggable
  has_many :tags, :through => :taggings

  has_attached_file :image, :styles => { :small => "100x100#", :medium => "250x250#" }
  
  validates :name, :uniqueness => true
  validates_presence_of :description, :image

  def to_param
    "#{name.downcase.gsub(/[^[:alnum:]]/,'-')}".gsub(/-{2,}/,'-')
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :admin_required, :except => [:index, :show]
  add_breadcrumb I18n.t('title.categories'), :categories_path
  
  def index
    @categories = Category.all
  end
  
  def new
    add_breadcrumb I18n.t('title.add_category'), :new_category_path
    @category = Category.new
  end
  
  def create
    @category = Category.new(params[:category])
    
    if @category.save
      redirect_to categories_url, :flash => { :success => I18n.t('notice.category_created') }
    else
      render :new
    end
  end
  
  def show
    @category = Category.find_by_name(params[:id])
    raise ActiveRecord::RecordNotFound unless @category
    @ads = Ad.find_by_tag_ids(@category.tags.select('tags.id'))
    add_breadcrumb @category.name, category_path(@category)
  end
  
  def edit
    @category = Category.find_by_name(params[:id])
    add_breadcrumb @category.name, category_path(@category)
  end
  
  def update
    @category = Category.find_by_name(params[:id])
    
    if @category.update_attributes(params[:category])
      redirect_to categories_url, :flash => { :success => I18n.t('notice.category_updated') }
    else
      render :edit
    end
  end
  
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    
    redirect_to categories_url
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def category_list(categories)
    elements = categories.map { |category| link_to category.name, category }
    elements.join(', ').html_safe
  end
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <%= f.error_messages %>
  
  <p id="category_name">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p id="category_description">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label "Category image" %><br />
    <%= f.file_field :image %>
  </p>
  <p>
    <%= f.submit %>
    <%= link_to 'Cancel', categories_path %>
  </p>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<% title t('title.categories') %>

<h1><%= t 'title.categories' %></h1>
<% if is_admin? %>
  <p class="add_category"><%= link_to t("title.add_category"), new_category_path %></p>
<% end %>

<div id="categories">
<% @categories.each do |category| %>
  <div id="category-<%= category.name %>" class="event_list_entry <%= cycle('even', 'odd') %> clearfix">
    <% if is_admin? %>
      <span class="icons-right"><%= link_to (image_tag 'delete.gif'), category, :confirm => I18n.t('help.delete_confirm_category'), :method => :delete %></span>
      <span class="icons-right"><%= link_to (image_tag 'edit.png'), edit_category_path(category) %></span>
    <% end %>
    <h1 class="category_name"><%= link_to category.name, category %></h1>
    <p class="category_description"><%= category.description %></p>
    <% if category.image.present? %>
      <%= link_to (image_tag category.image(:small), :class => "category_image"), category %>
    <% else %>
      <p class="category_image"></p>
    <% end %>
  </div>
<% end %>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<% title @category.name %>

<% content_for :ads do %>
  <%= elements_for_ads(@ads) %>
<% end %>

<header>
  <h1 class="show_category_name"><%= @category.name %>
    <% if is_admin? %>
      <span class="icons-right"><%= link_to (image_tag 'delete.gif'), @category, :confirm => I18n.t('help.delete_confirm_category'), :method => :delete %></span>
      <span class="icons-right"><%= link_to (image_tag 'edit.png'), edit_category_path(@category) %></span>
    <% end %>
  </h1>
</header>

<p class="show_category_description"><%= @category.description %></p>

<% if @category.image.present? %>
  <%= image_tag (@category.image(:medium)), :class => 'show_category_image' %>
<% else %>
  <p class="show_category_image"></p>
<% end %>

<h1>Events in <%= @category.name %></h1>

<% if @category.events.approved.any? %>
  <%- for event in @category.events.approved -%>
    <%= render event %>
  <%- end -%>
<% else %>
  <p><%= t 'help.empty_category' %></p>
<% end %>