config/routes.rb
NsgThesis::Application.routes.draw do
  scope "(:locale)", :locale => /en|fi/ do
    match "/auth/:provider/callback" => "sessions#create"
    match "/signin" => "sessions#signin", :as => :signin
    match "/signout" => "sessions#destroy", :as => :signout
    match "/myevents" => "events#my_events", :as => :myevents
  
  resources :events do
    resources :comments
    resources :galleries
    resources :hotels
    get 'unapproved', :on => :collection
    get 'approve', :on => :member
    get 'feed', :on => :collection
    get 'recent', :on => :collection
    get 'most_watched', :on => :collection
    get 'nearby', :on => :collection
    get 'upcoming', :on => :collection
    get 'like', :on => :member
  end

  resources :tags
  resources :categories
  resources :search do
    get 'advanced', :on => :collection
  end

  resources :ads do
    get 'unconfirmed', :on => :collection
    get 'confirm', :on => :member
    get 'my', :on => :collection
  end
  
  resources :clients do
    get 'unconfirmed', :on => :collection
    get 'confirm', :on => :member
  end

    root :to => 'home#index'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title).blank? ? 'Happen' : yield(:title) %></title>
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>
<div id="header_wrapper">
  <header id="page_header">
    <div class="top_group">
  		<div id="logo"><a href="#"></a></div> 
		  <div id="breadcrumb">
			<%=  render_breadcrumbs :separator => ' <img class="bread-split" src="/assets/bread_split.png" />  ' %>
		  </div>
        <nav id="user_nav">
        <% if current_user %>
          <%= current_user.name %>
          <%= link_to t('title.sign_out'), signout_path, :id => "signout" %>
        <% else %>
          <%= link_to t('title.sign_in'), signin_path, :id => "signin" %>
        <% end %>

        <a class="lang"><%= link_to_locales %></a>
        </nav>
      </div>
    <div class="recent_events">
      <%= upcoming_events(10) %>
    </div>
    <div id="search-box">
      <form action="<%= search_index_path %>" method="get">
        <input class="search-box" type="text" name="q" placeholder="<%= I18n.t('help.search') %>" />
        <input type="submit" class="submit" value="" />
      </form>
    </div>
		<div class="add_event">
		  <%= link_to t('title.add_event'), new_event_path %>
		</div>
      <nav id="page_nav">
        <ul>
          <li><%= link_to t('title.home'), root_path %></li>
          <li><%= link_to t('title.events'), events_path %></li>
          <li><%= link_to t('title.categories'), categories_path %></li>
          <li><%= link_to t('title.add_event'), new_event_path, :class => 'page_nav_last_link' %></li>
        </ul>
      </nav>
  </header>
</div>

<div id="wrapper">
  <section id="content">

    <% if request.path == root_path %>
    <div id="livemode">
    <span id="live">Live mode: </span> 
      <a href="#" id="toggle_live_mode"><img style="display:none" id="live_on" src="/assets/on25.png" /><img src="/assets/off25.png" id="live_off" /></a>  
    </div>
    <% end %>
      <p class="notification notice available_updates" style="display: none">
        <%= t 'content_has_been_updated' %>, 
        <a href="#" class="update_content_link"><%= t('show_updates') %></a>
        <a href="#" title="<%= I18n.t('help.close') %>" class="close"><%= image_tag 'cross-small-white.png' %></a>
      </p>

    <% flash.each do |name, msg| %>
        <p class="notification <%= name %>"><%= msg %> <a href="#" title="<%= I18n.t('help.close') %>" class="close_and_remove"><%= image_tag 'cross-small-white.png' %></a></p>
    <% end %>

    <%= yield %>
  </section>

  <aside>
    <% if current_user %>

      <%- if is_admin? -%>
      <h2><%= t 'title.confirmation_requests' %></h2>
      <nav id="requests">
        <ul>
          <li><span id="unapproved_events_count" class="request_count"> <%= Event.unapproved.count %></span> <%= link_to I18n.t('title.events'), unapproved_events_path %></li>
          <li><span id="unconfirmed_clients_count" class="request_count"><%= Client.unconfirmed.count %></span> <%= link_to I18n.t('title.clients'), unconfirmed_clients_path %></li>
          <li><span id="unconfirmed_ads_count" class="request_count"> <%= Ad.unconfirmed.count %></span> <%= link_to I18n.t('title.ads'), unconfirmed_ads_path %></li>
        </ul>
      </nav>
      <%- end -%>

      <% if is_admin? %>
      <br />
      <h2><%= t 'title.admin_links' %></h2>
      <nav id="adminlinks">
        <ul>
          <li><%= link_to I18n.t('title.clients'), clients_path %></li>
          <li><%= link_to t('title.ads'), ads_path %></li>
        </ul>
      </nav>
      <% end %>

      <br />
      <h2><%= t 'title.my_links' %></h2>
      <nav id="mylinks">
        <ul>
          <%- unless current_user.client_id.nil? -%>
          <li><%= link_to t('my_links.my_client'), current_user.client %></li>
          <% else %>
          <li><%= link_to t('my_links.new_client'), new_client_path %></li>
          <% end %>
          <li><%= link_to t('my_links.my_events'), myevents_path %></li>
          <li><%= link_to t('my_links.my_ads'), my_ads_path %></li>
          <li><%= link_to t('my_links.new_ad'), new_ad_path %></li>
        </ul>
      </nav>

      <br />
    <% end %>

    <div class="advertises">
      <%= content_for?(:ads) ? content_for(:ads) : elements_for_ads(Ad.confirmed) %>
    </div>

    <br />

    <h2><%= t 'title.tags' %></h2>
    <div class="tagcloud">
      <% tag_cloud %w(nube1 nube2 nube3 nube4 nube5) do |id, name, klass| %>
        <%= link_to name.downcase, tag_path(name), :class => klass %>
      <%- end -%>
    </div>
  </aside>

  <footer id="page_footer">
    <ul>
      <li> Copyright info </li>
      <li> Name & Date </li>
      <li> something else </li>
    </ul>
  </footer>
</div>
<script type="text/javascript">
var node_app_host = '<%= APP_HOST %>';
</script>
<script type="text/javascript" src="http://<%= APP_HOST %>:1337/socket.io/socket.io.js"></script>
<%= javascript_include_tag "application" %>
<%= yield(:head) %>
</body>
</html>